### PR TITLE
Add Redis Cache

### PR DESCRIPTION
**Pull request by etscrivner**
Add [redis](http://redis.io) cache backend.

**Explanation**

The organization I work for ([ParkMe](http://parkme.com)) are in the process of phasing out memcached in favor or redis. This pull request adds a redis cache backend to facilitate this transition.

### CODE REVIEW

**Comment by winkey** [comment]
is there a way to timestaamp a tile in the redis cache?

**Comment by winkey** [comment]
i guess i was asking if this can be done? https://github.com/OSGeo/tilecache/blob/master/tilecache/TileCache/Caches/Disk.py#L49

**Comment by etscrivner** [comment]
@winkey Not 100% sure I understand, but if you mean is there a way to expire tiles in the redis cache then absolutely. We currently use the [SETEX](http://redis.io/commands/setex) command to create a new key/value with a time-to-live (TTL) in seconds. Redis then takes care of deleting the key once it has expired. We could also use the [TTL](http://redis.io/commands/ttl) method to determine the remaining number of seconds a key has before expiration. If you'd like to store additional information, like a timestamp, along with the tile then we could use a [hashmap object](http://redis.io/commands#hash) and manually expire it.

**Comment by winkey** [comment]
well the idea is if each tile is timestamped, you can set a expire time on the layer in the config. then when the cache is acessed it checks if the tile is older that the timestamp in the config, if so it deletes the tile and requests a new one from the source. so whenever your data changes you just change the expire time in the config and the cache rebuilds itself on the fly

**Comment by etscrivner** [comment]
@winkey So that can absolutely be done by simply using a hash instead of a mere key/value store. This backend is merely meant to serve as a basic replacement for the memcached backend, but it could absolutely leverage the additional features in Redis to do more.

**Comment by winkey** [comment]
would that be something that you would be willing to add? all the work outside of the cache module is already done and quite well tested

**Comment by etscrivner** [comment]
I'll see what I can do, looks quite straightforward to add.

**Pull request merged**
